/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function paramsBn128(seed: number): void
export function proof(name: string, value: string, seed: number): void
export function verifyTheProof(name: string): void
export function totalPedCm(nameList: Array<string>): void
export function verifyPedTotalCm(): void
