/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function getRangeProofParamsGetBls12381(): void
export function getProof(name: string, value: string): void
export function verifyTheProof(name: string): void
export function getTotalPedCm(nameList: Array<string>): void
export function verifyPedTotalCm(): void
